[versions]
projectVersion = "0.0.18-SNAPSHOT"
projectVersionSelfApply = "0.0.17"
minJava = "21"
googleJavaFormat = "1.25.2"

[libraries]
buildoptions-plugin = "com.carrotsearch.gradle.opts:com.carrotsearch.gradle.opts.gradle.plugin:0.2.0"
dependencychecks-plugin = "com.carrotsearch.gradle.dependencychecks:com.carrotsearch.gradle.dependencychecks.gradle.plugin:0.1.0"
spotless-plugin = "com.diffplug.spotless:spotless-plugin-gradle:7.0.4"
forbiddenapis-plugin = "de.thetaphi:forbiddenapis:3.9"
benmanes-versions-plugin = "com.github.ben-manes:gradle-versions-plugin:0.52.0"
version-catalog-update-plugin = "nl.littlerobots.version-catalog-update:nl.littlerobots.version-catalog-update.gradle.plugin:1.0.0"
jackson-databind = "com.fasterxml.jackson.core:jackson-databind:2.19.1"
carrotsearch-procfork = "com.carrotsearch:procfork:1.0.6"
assertj = "org.assertj:assertj-core:4.0.0-M1"
junit-jupiter = "org.junit.jupiter:junit-jupiter:6.0.0"
spockframework = "org.spockframework:spock-bom:2.4-M6-groovy-3.0"

[plugins]
buildinfra = { id = "com.carrotsearch.gradle.buildinfra", version.ref = "projectVersionSelfApply" }
pluginpublish = "com.gradle.plugin-publish:1.3.1"
